### ISSUE TITLE
`vcruntime140d.dll` is missing

### ISSUE THREAD

**Issue by ftphikari** [Data-Oriented-House/PortableBuildTools#1]
Currently PBT unpacks files `vcruntime140d.dll_amd64` and `vcruntime140_1d.dll_amd64`, which do not get recognized by other programs because of the `_amd64` suffix. Odin, for example, will not work properly in debug mode, only `build 1` (release mode) works, just `build` will produce a binary that complains about lack of `vcruntime140d.dll`.

## TODO
Figure out what Visual Studio does with those files.

**Comment by ftphikari** [comment]
It seems that Visual Studio just renames those files, so on the TODO list:
1. Find all files in `%MSVC_BIN%` that end with `.dll_amd64` and rename them to `.dll`

**Comment by i486** [comment]
Please release the executable
