### ISSUE TITLE
cli doesn't handle invalid values well

### ISSUE THREAD

**Issue by milnak** [Data-Oriented-House/PortableBuildTools#12]
`portablebuildtools.exe cli accept_license msvc='14.40.33807' sdk='10.0.26100.0'`

ultimately fails with: 
`w:/dev/PortableBuildTools-master/src/install.odin(1000:37) Index 0 is out of range 0..<0`

should do validation and fail fast.

**Comment by milnak** [comment]
in addition, an invalid msvc version (as shown) doesn't fail.

**Comment by j-begin** [comment]
This has been fixed.

Thank you.
