### ISSUE TITLE
Installation fails/jams up when used with wine

### ISSUE THREAD

**Issue by mundusnine** [Data-Oriented-House/PortableBuildTools#14]
For reference, I use SteamOS btw(it's arch basically).
![image](https://github.com/Data-Oriented-House/PortableBuildTools/assets/29337013/45efd2a1-77a1-4749-ab44-d2860a757c3f)

Here is a [backtrace.txt](https://github.com/user-attachments/files/15915092/backtrace.txt) of the error.

I tried using sudo to see if permissions would be an issue. Did not help.

Here is where it jams:
![image](https://github.com/Data-Oriented-House/PortableBuildTools/assets/29337013/3a505376-f4f9-4943-a0b0-d20d3dca870f)

**Comment by munohikari** [comment]
@mundusnine By the way, i just tested the latest version on latest Xubuntu, works fine, so there you go, i guess it fixed itself after a rewrite.

**Comment by munohikari** [comment]
Just tried with Fedora, it breaks for me with a different error... well, whatever, it's not a problem on my end, wine guys should just fix their stuff.
