### ISSUE TITLE
2.2: Fails if dest folder exists

### ISSUE THREAD

**Issue by milnak** [Data-Oriented-House/PortableBuildTools#18]
would be nice to have a "force" option in console to overwrite existing, to allow for in-place upgrades.

**Comment by munohikari** [comment]
If you want to have that in a shell script, then just delete the contents with a prior command. If you want to use a GUI for that, then just delete the contents manually. There are no "in-place upgrades" for this kind of stuff, the structure might be very different, the old files might be left, new ones might be added, etc.
