### ISSUE TITLE
libomp140.x86_64.dll Missing

### ISSUE THREAD

**Issue by harshn05** [Data-Oriented-House/PortableBuildTools#23]
Just tested the latest version of **PortableBuildTools 2.5** with **MSVC 14.41.17.11**, the **26100 SDK**, and **Clang 18.1.8**. The host and target architecture were both x64. To be precise, I am using Clang as the compiler while leveraging the MSVC toolchain and libraries for linking and other build processes.

For testing,  [a CMake-based C++ program](https://github.com/harshn05/ImGuiVoronoiGen) of mine which includes complex dependencies such as stb_image, GLEW, GLFW, OpenGL, ImGUI, OpenMP etc, compiled successfully. However, when running the executable, the **libomp140.x86_64.dll** was missing. It appears that the portable installation did not include **libomp140.x86_64.dll** (and possibly other necessary DLLs?). 

In an older installation of MSVC with PortableBuildTools, **libomp140.x86_64.dll** was available.

**Comment by munohikari** [comment]
Indeed, the method of installation has changed recently to make it work with new SDKs. Please report this issue [here](https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977), since i use Martins' implementation as a base for this GUI.

**Comment by harshn05** [comment]
Thanks I have reported the issue as suggested by you.
For the time being as a workaround, I have downgraded the MSVC_Version to: 14.40 keeping the latest SDK version (26100).

**Comment by harshn05** [comment]
This has been fixed upstream by Mārtiņš and hence can be closed.

**Comment by munohikari** [comment]
Please try this version: https://github.com/Data-Oriented-House/PortableBuildTools/releases/download/v2.6/PortableBuildTools.exe

**Comment by harshn05** [comment]
Working as expected, so closing this issue
Thanks for this project.
