### ISSUE TITLE
pip still not recognizing installation

### ISSUE THREAD

**Issue by bzv3** [Data-Oriented-House/PortableBuildTools#4]
I have installed PortableBuildTools, ensured that all the relevant paths are on my %PATH% as well as other system environment variables, and rebooted my machine as per the GUI installer instructions.

And pip still cannot build modules that require Microsoft Visual C++ 14.0 or higher.

I have killed/restarted the terminal in VS Code where I am working.

Any further suggestions? Thanks!

**Comment by Donaldduck8** [comment]
You may need to set an environment variable called "DISTUTILS_USE_SDK" to "1". After doing that, I was able to `pip install netifaces` which requires build tools.

For reference, see https://github.com/pypa/setuptools/blob/0156e248e777eebff9250d83603611585d0c8f12/setuptools/msvc.py#L182C9-L182C26

**Comment by j-begin** [comment]
I am closing this for now.
