### ISSUE TITLE
Setup failed due to PATH errors

### ISSUE THREAD

**Issue by LinArcX** [Data-Oriented-House/PortableBuildTools#5]
I tried to install PortableBuildToosl. but at the end of installation phase, i get this error:
![Capture](https://github.com/Data-Oriented-House/PortableBuildTools/assets/10884422/7bc33b9a-75a9-4242-b03b-ff3bcaf73c58)

**Comment by LinArcX** [comment]
On my machine this env is Path not PATH. i tried to make it capital letter. but still have the same problem.

**Comment by LinArcX** [comment]
Seems PATH has a maximum length. I watched my PATH and there were lots of entries in it. I tried to remove some of them to make more space for PortableBuildTools. but still have this issue. did you check the length of PATH before adding new envs to it?

https://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-window

**Comment by joakin** [comment]
I just had this same issue. After a restart I was able to build the Odin compiler fine, but I get LLVM error now when I try to compile my project.

**Comment by Ronin15** [comment]
Having the same issue as well.

**Comment by Ronin15** [comment]
Figured this out. I was having the issue as well. If you already had user var set for path then it will throw the error. Copy your user path var contents. Run the tool then add your vars after the tool set its vars :)

**Comment by j-begin** [comment]
I think this has been fixed. Test it on your end.
