### ISSUE TITLE
Batch script suggestion

### ISSUE THREAD

**Issue by AlessioR** [Data-Oriented-House/PortableBuildTools#7]
Hi,
first of all thank you for your program, it's very useful.
A little advice, wouldn't it be better to modify the batch script in the following way to make it truly portable?

```
@echo off

set PORTABLE_BUILD_TOOLS_PATH=%~dp0

set WindowsSDKDir=%PORTABLE_BUILD_TOOLS_PATH%\Windows Kits\10
set WindowsSDKVersion=10.0.19041.0
set VCToolsInstallDir=%PORTABLE_BUILD_TOOLS_PATH%\VC\Tools\MSVC\14.39.33519\
set VSCMD_ARG_TGT_ARCH=x64
...
```

in this way we can avoid having the absolute path specified multiple time.

**Comment by j-begin** [comment]
This has been fixed.

Thank you.
